import React, { useState, useMemo } from 'react';
import { View, StyleSheet, FlatList, Alert, Linking } from 'react-native';
import { FAB, Text, useTheme } from 'react-native-paper';
import { SafeAreaView } from 'react-native-safe-area-context';
import LinkCard from '../components/LinkCard';
import FilterBar from '../components/FilterBar';
import SearchBar from '../components/SearchBar';
import AddLinkModal from '../components/AddLinkModal';
import DateFilterModal, { DateFilterOption } from '../components/DateFilterModal';
import { MOCK_LINKS, FILTER_CHIPS, Link } from '../data/mockData';

import { generateResponse } from '../ai';

const DashboardScreen = () => {
  const theme = useTheme();

  // For testing AI integration
  React.useEffect(() => {
    const testLlm = async () => {
      try {
        const result = await generateResponse(
          "Generate a title, description and tags for the following link: https://github.com/resemble-ai/chatterbox." +
          "Title should be short/crisp. The description should be concise and informative like tldr in 1-2 sentences max. Provide max 3 relevant tags."
        );
        console.log(result);
      } catch (error) {
        console.error("AI Generation failed:", error);
      }
    };

    testLlm();
  }, []);

  const [links, setLinks] = useState<Link[]>(MOCK_LINKS);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFilter, setSelectedFilter] = useState('all');
  const [isAddModalVisible, setIsAddModalVisible] = useState(false);
  const [isDateFilterVisible, setIsDateFilterVisible] = useState(false);
  const [selectedDateFilter, setSelectedDateFilter] = useState<DateFilterOption>('all');

  const getDateFilterRange = (filter: DateFilterOption): Date | null => {
    const now = new Date();
    switch (filter) {
      case 'today':
        const today = new Date(now);
        today.setHours(0, 0, 0, 0);
        return today;
      case 'last7days':
        return new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
      case 'last30days':
        return new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
      case 'last6months':
        return new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
      case 'lastyear':
        return new Date(now.getTime() - 365 * 24 * 60 * 60 * 1000);
      default:
        return null;
    }
  };

  const filteredLinks = useMemo(() => {
    return links.filter((link) => {
      const matchesSearch = 
        link.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        link.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        link.url.toLowerCase().includes(searchQuery.toLowerCase());
      
      const matchesFilter = 
        selectedFilter === 'all' || 
        link.tags.some(tag => tag.toLowerCase().includes(selectedFilter.toLowerCase().replace('#', '')));

      // Date filter
      const dateFilterRange = getDateFilterRange(selectedDateFilter);
      const matchesDateFilter = !dateFilterRange || new Date(link.addedAt) >= dateFilterRange;

      return matchesSearch && matchesFilter && matchesDateFilter;
    });
  }, [links, searchQuery, selectedFilter, selectedDateFilter]);

  const handleAddLink = (url: string) => {
    // Simulate AI Enrichment
    const newLink: Link = {
      id: Date.now().toString(),
      url,
      title: 'New Enriched Link',
      description: 'This is a simulated enriched link description generated by "AI".',
      type: 'web',
      source: 'Web',
      tags: ['#New', '#ReadLater'],
      metadata: {
        author: 'Unknown Author',
        readTime: '5 min read',
      },
      addedAt: new Date().toISOString(),
      status: 'unread',
      scheduledFor: null,
    };

    setLinks([newLink, ...links]);
    setIsAddModalVisible(false);
    // Simulate toast
    Alert.alert("Saved to Parcit", "Link enriched and added to your queue.");
  };

  const handleSchedule = (id: string) => {
    const item = links.find(l => l.id === id);
    if (!item) return;
    
    // Toggle: If already scheduled, unschedule it
    if (item.scheduledFor) {
      setLinks(prev => prev.map(l => 
        l.id === id ? { ...l, scheduledFor: null, status: 'unread' } : l
      ));
      return;
    }
    
    // Simulate deep linking to Google Calendar
    const title = encodeURIComponent(`Read: ${item.title}`);
    const details = encodeURIComponent(`Original URL: ${item.url}\n\nSummary: ${item.description || ''}`);
    const gCalUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}`;
    
    // Open Calendar
    Linking.openURL(gCalUrl).catch(err => console.error("Couldn't load page", err));

    // Update state
    setLinks(prev => prev.map(l => l.id === id ? { ...l, scheduledFor: new Date().toISOString(), status: 'scheduled' } : l));
  };

  const handleMarkRead = (id: string) => {
      const item = links.find(l => l.id === id);
      if (!item) return;
      
      // Toggle: If already read, mark as unread
      if (item.status === 'read') {
        setLinks(prev => prev.map(l => 
          l.id === id ? { ...l, status: 'unread' } : l
        ));
      } else {
        setLinks(prev => prev.map(l => l.id === id ? { ...l, status: 'read' } : l));
      }
  };

  const handleDateFilter = () => {
      setIsDateFilterVisible(true);
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={styles.header}>
          <Text variant="headlineMedium" style={styles.appTitle}>Parcit</Text>
      </View>
      
      <SearchBar 
        value={searchQuery} 
        onChangeText={setSearchQuery} 
        onFilterPress={handleDateFilter}
        isFilterActive={selectedDateFilter !== 'all'}
      />
      <FilterBar 
        filters={FILTER_CHIPS} 
        selectedFilter={selectedFilter} 
        onSelectFilter={setSelectedFilter} 
      />

      <FlatList
        data={filteredLinks}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <LinkCard 
            item={item} 
            onSchedule={handleSchedule}
            onMarkRead={handleMarkRead}
          />
        )}
        contentContainerStyle={styles.listContent}
        ListEmptyComponent={
            <View style={styles.emptyState}>
                <Text variant="bodyLarge" style={{ color: theme.colors.onSurfaceVariant }}>
                    Nothing found. Try clearing filters or adding a new link.
                </Text>
            </View>
        }
      />

      <FAB
        icon="plus"
        style={[styles.fab, { backgroundColor: theme.colors.primary }]}
        color="white"
        onPress={() => setIsAddModalVisible(true)}
      />

      <AddLinkModal
        visible={isAddModalVisible}
        onDismiss={() => setIsAddModalVisible(false)}
        onSave={handleAddLink}
      />

      <DateFilterModal
        visible={isDateFilterVisible}
        onDismiss={() => setIsDateFilterVisible(false)}
        selectedFilter={selectedDateFilter}
        onSelectFilter={setSelectedDateFilter}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
      paddingHorizontal: 16,
      paddingVertical: 8,
  },
  appTitle: {
      fontWeight: 'bold',
      color: '#1a1a2e',
  },
  listContent: {
    padding: 16,
    paddingBottom: 80, // Space for FAB
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 35,
    borderRadius: 16,
  },
  emptyState: {
      alignItems: 'center',
      marginTop: 40,
      paddingHorizontal: 20,
  }
});

export default DashboardScreen;
