import React, { useState, useMemo } from 'react';
import { View, StyleSheet, FlatList, Alert, Linking } from 'react-native';
import { FAB, Text, useTheme } from 'react-native-paper';
import { SafeAreaView } from 'react-native-safe-area-context';
import LinkCard from '../components/LinkCard';
import FilterBar from '../components/FilterBar';
import SearchBar from '../components/SearchBar';
import AddLinkModal from '../components/AddLinkModal';
import { MOCK_LINKS, FILTER_CHIPS } from '../data/mockData';

const DashboardScreen = () => {
  const theme = useTheme();
  const [links, setLinks] = useState(MOCK_LINKS);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFilter, setSelectedFilter] = useState('all');
  const [isAddModalVisible, setIsAddModalVisible] = useState(false);

  const filteredLinks = useMemo(() => {
    return links.filter((link) => {
      const matchesSearch = 
        link.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        link.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        link.url.toLowerCase().includes(searchQuery.toLowerCase());
      
      const matchesFilter = 
        selectedFilter === 'all' || 
        link.tags.some(tag => tag.toLowerCase().includes(selectedFilter.toLowerCase().replace('#', '')));

      return matchesSearch && matchesFilter;
    });
  }, [links, searchQuery, selectedFilter]);

  const handleAddLink = (url) => {
    // Simulate AI Enrichment
    const newLink = {
      id: Date.now().toString(),
      url,
      title: 'New Enriched Link',
      description: 'This is a simulated enriched link description generated by "AI".',
      type: 'web',
      source: 'Web',
      tags: ['#New', '#ReadLater'],
      metadata: {
        author: 'Unknown Author',
        readTime: '5 min read',
      },
      addedAt: new Date().toISOString(),
      status: 'unread',
      scheduledFor: null,
    };

    setLinks([newLink, ...links]);
    setIsAddModalVisible(false);
    // Simulate toast
    Alert.alert("Saved to Parcit", "Link enriched and added to your queue.");
  };

  const handleSchedule = (item) => {
    // Simulate deep linking to Google Calendar
    const title = encodeURIComponent(`Read: ${item.title}`);
    const details = encodeURIComponent(`Original URL: ${item.url}\n\nSummary: ${item.description || ''}`);
    const gCalUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}`;
    
    // Open Calendar
    Linking.openURL(gCalUrl).catch(err => console.error("Couldn't load page", err));

    // Update state
    setLinks(prev => prev.map(l => l.id === item.id ? { ...l, scheduledFor: new Date().toISOString(), status: 'scheduled' } : l));
    
    // Simulate toast
    Alert.alert("Opening Calendar...", "Please save the event in your calendar app.");
  };

  const handleMarkRead = (item) => {
      setLinks(prev => prev.map(l => l.id === item.id ? { ...l, status: 'read' } : l));
      Alert.alert("Marked as Read", `"${item.title}" has been marked as read.`);
  };

  const handleArchive = (item) => {
      Alert.alert(
          "Archive", 
          "Are you sure you want to archive this link?",
          [
              { text: "Cancel", style: "cancel" },
              { 
                  text: "Archive", 
                  onPress: () => {
                      setLinks(links.filter(l => l.id !== item.id));
                  }
              }
          ]
      );
  };

  const handleDateFilter = () => {
      Alert.alert("Date Filter", "Date range picker would open here.");
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={styles.header}>
          <Text variant="headlineMedium" style={styles.appTitle}>Parcit</Text>
      </View>
      
      <SearchBar 
        value={searchQuery} 
        onChangeText={setSearchQuery} 
        onFilterPress={handleDateFilter}
      />
      <FilterBar 
        filters={FILTER_CHIPS} 
        selectedFilter={selectedFilter} 
        onSelectFilter={setSelectedFilter} 
      />

      <FlatList
        data={filteredLinks}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <LinkCard 
            item={item} 
            onSchedule={handleSchedule}
            onMarkRead={handleMarkRead}
            onArchive={handleArchive}
          />
        )}
        contentContainerStyle={styles.listContent}
        ListEmptyComponent={
            <View style={styles.emptyState}>
                <Text variant="bodyLarge" style={{ color: theme.colors.onSurfaceVariant }}>
                    Nothing found. Try clearing filters or adding a new link.
                </Text>
            </View>
        }
      />

      <FAB
        icon="plus"
        style={[styles.fab, { backgroundColor: theme.colors.primary }]}
        color="white"
        onPress={() => setIsAddModalVisible(true)}
      />

      <AddLinkModal
        visible={isAddModalVisible}
        onDismiss={() => setIsAddModalVisible(false)}
        onSave={handleAddLink}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
      paddingHorizontal: 16,
      paddingVertical: 8,
  },
  appTitle: {
      fontWeight: 'bold',
      color: '#1a1a2e',
  },
  listContent: {
    padding: 16,
    paddingBottom: 80, // Space for FAB
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 35,
    borderRadius: 16,
  },
  emptyState: {
      alignItems: 'center',
      marginTop: 40,
      paddingHorizontal: 20,
  }
});

export default DashboardScreen;
